### ISSUE TITLE
No implementation found for long com.artifex.mupdfdemo.MuPDFCore.openFile(java.lang.String) (tried Java_com_artifex_mupdfdemo_MuPDFCore_openFile and Java_com_artifex_mupdfdemo_MuPDFCore_openFile__Ljava_lang_String_2)

### ISSUE THREAD

**Issue by 1uokun** [LonelyPluto/PdfViewerDemo#1]
## Question Description
App crash when click any button to open pdf

##### LogCat
```
E/BasePDFActivity: Trying to open /storage/emulated/0/pdf_t1.pdf
E/MuPDFCore: Loading dll
E/MuPDFCore: Loaded dll
E/o.pdfviewerdem: No implementation found for long com.artifex.mupdfdemo.MuPDFCore.openFile(java.lang.String) (tried Java_com_artifex_mupdfdemo_MuPDFCore_openFile and Java_com_artifex_mupdfdemo_MuPDFCore_openFile__Ljava_lang_String_2)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lonelypluto.pdfviewerdemo, PID: 22705
    java.lang.UnsatisfiedLinkError: No implementation found for long com.artifex.mupdfdemo.MuPDFCore.openFile(java.lang.String) (tried Java_com_artifex_mupdfdemo_MuPDFCore_openFile and Java_com_artifex_mupdfdemo_MuPDFCore_openFile__Ljava_lang_String_2)
        at com.artifex.mupdfdemo.MuPDFCore.openFile(Native Method)
        at com.artifex.mupdfdemo.MuPDFCore.<init>(MuPDFCore.java:138)
        at com.lonelypluto.pdfviewerdemo.activity.BasePDFActivity.openFile(BasePDFActivity.java:87)
        at com.lonelypluto.pdfviewerdemo.activity.BasePDFActivity.initView(BasePDFActivity.java:54)
        at com.lonelypluto.pdfviewerdemo.activity.BasePDFActivity.onCreate(BasePDFActivity.java:44)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process: Sending signal. PID: 22705 SIG: 9
Application terminated.

```

## device
simulator in Android Studio

Name|Resolution|API|Target|CPU/ABI|
|----|----|----|----|----|
|Nexus 7 API 25 |1200 x 1920: xhdpi|25 |  Android 7.1.1(Google APIs) | x86 |

## 我做了哪些努力
在真机中正常
通过搜索引擎查出是仅支持`CPU/ABI`为`armeabi-v7a`的设备，
但是在
```bash
$ git clone git://git.ghostscript.com/mupdf-android-viewer.git
```
这个项目下是可以跑`x86`模拟器的。
#### [请问https://github.com/joniks/Android-MuPDF这个库和官方库的主要区别或者说做了哪些改变吗❓](https://github.com/joniks/Android-MuPDF)

**Comment by LonelyPluto** [comment]
很抱歉，主要是在编译.so文件时我只编译了armeabi-v7a而没有编译x86的，支持哪种ABI只需在编译.so文件时选择生成就可以。你说的Android-MuPDF这个库应该是编译了多个.so，希望我的回答能够帮到你

**Comment by LonelyPluto** [comment]
@1uokun  很抱歉，主要是在编译.so文件时我只编译了armeabi-v7a而没有编译x86的，支持哪种ABI只需在编译.so文件时选择生成就可以。你说的Android-MuPDF这个库应该是编译了多个.so，希望我的回答能够帮到你

**Comment by 1uokun** [comment]
在下一个版本中是否可以考虑到尽可能为每种CPU类型都提供对应的SO库呢

**Comment by LonelyPluto** [comment]
@1uokun  非常感谢你的建议，我会尽快更新下个版本支持更多CPU的类型

**Comment by 1uokun** [comment]
1.0.6版本完美解决🎉🎉🎉，请关闭issue

**Comment by sunchangdong** [comment]
首先感谢你提供了这个公开库，正发愁不知道怎么使用mupdf呢。现在使用了最新的1.0.6版本，发现在进行添加批注的时候，在正常展示和放大展示两种状态下，画笔的粗细设置一样，但是将批注保存后，显示的批注粗细不一样

**Comment by gaoerhan** [comment]
No implementation found for long com.lonelypluto.pdfviewerdemo.artifex.mupdfdemo.MuPDFCore.openFile(java.lang.String)，我这里报这个错，是so库有问题吗
